logging.level:
  root: WARN
  ru.on8off.kafka: INFO
application.id: "kafka-steams-lesson"
schema-registry: "http://localhost:8081"
bootstrap-servers: "localhost:9092"
partitions: 1
replications: 1
topics:
  source: paymentEventsAvroTopic
  payments: paymentsTopic
  paymentsSuccess: paymentsSuccessTopic
  paymentsFiled: paymentsFailedTopic
  paymentsAbandoned: paymentsAbandonedTopic